-- app_data
CREATE USER app_data IDENTIFIED BY "hv0ttSh34p4HpC2"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_code
CREATE USER app_code IDENTIFIED BY "In8j1Z22FahaAuz"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_admin
CREATE USER app_admin IDENTIFIED BY "1kjCmVHNGtVlBfp"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_user
CREATE USER app_user IDENTIFIED BY "EOpfAR8U9fZt90i"
ENABLE EDITIONS;